dependencies:
  - docker

executionClients:
  - nethermind
  - geth
  - erigon
  - besu

consensusClients:
  - lighthouse
  - lodestar
  - prysm
  - teku
 
validatorClients:
  - lighthouse
  - lodestar
  - prysm
  - teku

logs:
  logLevel: debug