execution:
  geth:
    name: ethereum/client-go
    version: v1.12.1
  besu:
    name: hyperledger/besu
    version: 23.4.4
  nethermind:
    name: nethermind/nethermind
    version: 1.20.1
  erigon:
    name: thorax/erigon
    version: v2.48.1
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v4.3.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.9.2
  teku:
    name: consensys/teku
    version: 23.8.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v4.0.7
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v4.3.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.9.2
  teku:
    name: consensys/teku
    version: 23.8.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v4.0.7
starknet:
  juno:
    name: nethermind/juno
    version: v0.7.0

