execution:
  geth:
    name: ethereum/client-go
    version: v1.12.0
  besu:
    name: hyperledger/besu
    version: 23.4.1
  nethermind:
    name: nethermind/nethermind
    version: 1.19.0
  erigon:
    name: thorax/erigon
    version: v2.44.0
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v4.2.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.8.0
  teku:
    name: consensys/teku
    version: 23.5.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v4.0.5
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v4.2.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.8.0
  teku:
    name: consensys/teku
    version: 23.5.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v4.0.5
