execution:
  geth:
    name: ethereum/client-go
    version: v1.13.11
  besu:
    name: hyperledger/besu
    version: 24.1.1
  nethermind:
    name: nethermind/nethermind
    version: 1.25.3
  erigon:
    name: thorax/erigon
    version: v2.57.1
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v4.6.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.15.0-rc.0
  teku:
    name: consensys/teku
    version: 24.1.1
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v4.2.1-rc.2
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v4.6.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.15.0-rc.0
  teku:
    name: consensys/teku
    version: 24.1.1
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v4.2.1-rc.2