execution:
  geth:
    name: ethereum/client-go:v1.10.26
    version: v1.10.26
  besu:
    name: hyperledger/besu
    version: 23.1.0
  nethermind:
    name: nethermind/nethermind
    version: 1.17.0
  erigon:
    name: thorax/erigon
    version: v2.38.0
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v3.5.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.4.3
  teku:
    name: consensys/teku
    version: 23.2.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v3.2.1
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v3.5.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.4.3
  teku:
    name: consensys/teku
    version: 23.2.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v3.2.1
