execution:
  geth:
    name: ethereum/client-go
    version: v1.13.0
  besu:
    name: hyperledger/besu
    version: 23.7.2
  nethermind:
    name: nethermind/nethermind
    version: 1.20.2
  erigon:
    name: thorax/erigon
    version: v2.49.1
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v4.4.1
  lodestar:
    name: chainsafe/lodestar
    version: v1.11.0
  teku:
    name: consensys/teku
    version: 23.9.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v4.1.0
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v4.3.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.9.2
  teku:
    name: consensys/teku
    version: 23.8.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v4.0.7
