execution:
  geth:
    name: ethereum/client-go
    version: v1.13.14
  besu:
    name: hyperledger/besu
    version: 24.3.0
  nethermind:
    name: nethermind/nethermind
    version: 1.25.4
  erigon:
    name: thorax/erigon
    version: v2.58.1
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v5.0.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.16.0
  teku:
    name: consensys/teku
    version: 24.3.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v5.0.0
  nimbus:
    name: statusim/nimbus-eth2
    version: multiarch-v24.3.0
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v5.0.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.16.0
  teku:
    name: consensys/teku
    version: 24.3.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v5.0.0
  nimbus:
    name: statusim/nimbus-validator-client
    version: multiarch-v24.5.1