execution:
  geth:
    name: ethereum/client-go
    version: v1.11.5
  besu:
    name: hyperledger/besu
    version: 23.1.1
  nethermind:
    name: nethermind/nethermind
    version: 1.17.2
  erigon:
    name: thorax/erigon
    version: v2.40.1
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v3.5.1
  lodestar:
    name: chainsafe/lodestar
    version: v1.6.0
  teku:
    name: consensys/teku
    version: 23.3.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v3.2.2
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v3.5.1
  lodestar:
    name: chainsafe/lodestar
    version: v1.6.0
  teku:
    name: consensys/teku
    version: 23.3.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v3.2.2
