execution:
  geth:
    name: ethereum/client-go
    version: v1.13.4
  besu:
    name: hyperledger/besu
    version: 23.7.2
  nethermind:
    name: nethermind/nethermind
    version: 1.21.0
  erigon:
    name: thorax/erigon
    version: v2.52.5
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v4.5.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.11.3
  teku:
    name: consensys/teku
    version: 23.9.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v4.1.0
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v4.5.0
  lodestar:
    name: chainsafe/lodestar
    version: v1.11.3
  teku:
    name: consensys/teku
    version: 23.9.0
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v4.1.0
starknet:
  juno:
    name: nethermind/juno
    version: v0.7.0
