execution:
  geth:
    name: ethereum/client-go
    version: v1.14.6
  besu:
    name: hyperledger/besu
    version: 24.6.0
  nethermind:
    name: nethermind/nethermind
    version: 1.27.0
  erigon:
    name: thorax/erigon
    version: v2.60.2
consensus:
  lighthouse:
    name: sigp/lighthouse
    version: v5.2.1
  lodestar:
    name: chainsafe/lodestar
    version: v1.19.0
  teku:
    name: consensys/teku
    version: 24.6.1
  prysm:
    name: gcr.io/prysmaticlabs/prysm/beacon-chain
    version: v5.0.4
validator:
  lighthouse:
    name: sigp/lighthouse
    version: v5.2.1
  lodestar:
    name: chainsafe/lodestar
    version: v1.19.0
  teku:
    name: consensys/teku
    version: 24.6.1
  prysm:
    name: gcr.io/prysmaticlabs/prysm/validator
    version: v5.0.4
distributed:
  charon:
    name: ghcr.io/obolnetwork/charon
    version: v0.19.2
