name: 'Build Sedge'

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'The TAG of the version you want to release.'
        required: false
        default: 'master'

permissions: 
  packages: write

jobs:
  build_sedge:
    name: Build sedge
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.3'
    - run: chmod +x ./scripts/build-go-binaries.sh && ./scripts/build-go-binaries.sh
    - uses: actions/upload-artifact@master
      name: Uploading sedge darwin amd64 package
      with:
        name: sedge-darwin-amd64-package
        path: build/sedge-darwin-amd64

    - uses: actions/upload-artifact@master
      name: Uploading sedge darwin arm64 package
      with:
        name: sedge-darwin-arm64-package
        path: build/sedge-darwin-arm64

    - uses: actions/upload-artifact@master
      name: Uploading sedge linux amd64 package
      with:
        name: sedge-linux-amd64-package
        path: build/sedge-linux-amd64
        
    - uses: actions/upload-artifact@master
      name: Uploading sedge linux arm64 package
      with:
        name: sedge-linux-arm64-package
        path: build/sedge-linux-arm64

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64, arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}


  upload-sedge:
    runs-on: ubuntu-latest
    steps:
    - name: Download packages
      uses: actions/download-artifact@v3
      with: 
        path: /tmp/binaries
    - name: Upload release to Github Releases
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          /tmp/binaries/sedge-linux-amd64
          /tmp/binaries/sedge-linux-arm64
          /tmp/binaries/sedge-darwin-amd64
          /tmp/binaries/sedge-darwin-arm64