name: 'Build Sedge'

on:
  push:

jobs:
  build_sedge:
    name: Build sedge
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.3'
    - run: chmod +x ./scripts/build-go-binaries.sh && ./scripts/build-go-binaries.sh
    - uses: actions/upload-artifact@master
      name: Uploading sedge darwin amd64 package
      with:
        name: sedge-darwin-amd64-package
        path: build/sedge-darwin-amd64

    - uses: actions/upload-artifact@master
      name: Uploading sedge darwin arm64 package
      with:
        name: sedge-darwin-arm64-package
        path: build/sedge-darwin-arm64

    - uses: actions/upload-artifact@master
      name: Uploading sedge linux amd64 package
      with:
        name: sedge-linux-amd64-package
        path: build/sedge-linux-amd64
        
    - uses: actions/upload-artifact@master
      name: Uploading sedge linux arm64 package
      with:
        name: sedge-linux-arm64-package
        path: build/sedge-linux-arm64