name: Check Docker images for updates

on:
  push:
    branches: 
      - develop

jobs:
  build:
    name: Check for updates
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sedge repo
      uses: actions/checkout@v2

    - name: Run update check script
      run: chmod +x ./scripts/check-image-updates.sh && ./scripts/check-image-updates.sh
      env:
        PAT: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
        commit-message: Update image versions to latest version.
        title: '[Update] Update image versions'
        reviewers: falcoxyz, AntiD2ta, cbermudez97
        branch: feature/update-container-images
        draft: false