name: sedge unit tests
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  unit_tests:
    name: Run unit tests
    strategy:
      matrix:
        go: ["1.18.2"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Install deps
        run: make install-deps

      - name: Run tests ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: make codecov-test

      - name: Run tests windows
        if: matrix.os == 'windows-latest'
        run: go test ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          fail_ci_if_error: true
          files: ./coverage/coverage.out
          flags: unittests
          name: codecov-umbrella
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
